// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXdX_CPxGPoL99S-1mTImRG8YcBuJcT3Q',
    appId: '1:978052084753:web:d04eacedeb657c1188adb0',
    messagingSenderId: '978052084753',
    projectId: 'farms-eth',
    authDomain: 'farms-eth.firebaseapp.com',
    storageBucket: 'farms-eth.appspot.com',
    measurementId: 'G-YGQSD7MHBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB06SwlWL6UziCI0PNgkEkw0cYYaGnUe6Y',
    appId: '1:978052084753:android:d651d266d73ca78488adb0',
    messagingSenderId: '978052084753',
    projectId: 'farms-eth',
    storageBucket: 'farms-eth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyZ248AfdlS7dYOIbrwK9crLbuA9t6hTo',
    appId: '1:978052084753:ios:61bc78788d58502388adb0',
    messagingSenderId: '978052084753',
    projectId: 'farms-eth',
    storageBucket: 'farms-eth.appspot.com',
    iosBundleId: 'com.example.farms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyZ248AfdlS7dYOIbrwK9crLbuA9t6hTo',
    appId: '1:978052084753:ios:89959d2b0a1246b288adb0',
    messagingSenderId: '978052084753',
    projectId: 'farms-eth',
    storageBucket: 'farms-eth.appspot.com',
    iosBundleId: 'com.example.farms.RunnerTests',
  );
}
